# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 13:48
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_add_polymorphic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_id', models.CharField(blank=True, help_text="The transaction processor's reference", max_length=255, null=True, verbose_name='Shipping ID')),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fulfilled at')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Shipped at')),
                ('shipping_method', models.CharField(help_text='The shipping backend used to deliver the items for this order', max_length=50, verbose_name='Shipping method')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.Order')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Delivered quantity')),
                ('delivery', models.ForeignKey(help_text='Refer to the shipping provider used to ship this item', on_delete=django.db.models.deletion.CASCADE, to='myshop.Delivery', verbose_name='Delivery')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name='Item canceled '),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='unit_price',
            field=django.db.models.fields.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Net price for this product', max_digits=30),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='amount',
            field=django.db.models.fields.DecimalField(decimal_places=2, default=Decimal('0'), help_text='How much was paid with this particular transfer.', max_digits=30),
        ),
        migrations.AlterField(
            model_name='smartcard',
            name='unit_price',
            field=django.db.models.fields.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Net price for this product', max_digits=30),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='unit_price',
            field=django.db.models.fields.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Net price for this product', max_digits=30),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.OrderItem', verbose_name='Ordered item'),
        ),
    ]
