# Generated by Django 2.1.10 on 2019-07-19 18:23                                                                                                                                                              
from django import VERSION as DJANGO_VERSION

DJANGO111 = True if DJANGO_VERSION < (2, 0) else False

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_auth', '0004_auto_20170411_1733'),
    ]
    if not DJANGO111:
        operations = [
            migrations.AlterField(
                model_name='user',
                name='last_name',
                field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
            ),
        ]
