# Generated by Django 2.1.10 on 2019-07-19 18:26

from django import VERSION as DJANGO_VERSION

DJANGO111 = True if DJANGO_VERSION < (2, 0) else False

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_delete_email'),
    ]
    if not DJANGO111:
        operations = [
            migrations.AlterField(
                model_name='notification',
                name='mail_template',
                field=models.ForeignKey(limit_choices_to=models.Q(('language__isnull', True), ('language', ''), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='post_office.EmailTemplate', verbose_name='Template'),
            ),
            migrations.AlterField(
                model_name='notification',
                name='recipient',
                field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
            ),
        ]
